<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAQbmx9U\srcDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAQbmx9U/srcDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAQbmx9U.legacy');

    return;
}

if (!\class_exists(srcDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAQbmx9U\srcDebugProjectContainer::class, srcDebugProjectContainer::class, false);
}

return new \ContainerAQbmx9U\srcDebugProjectContainer(array(
    'container.build_hash' => 'AQbmx9U',
    'container.build_id' => 'dab3ea2e',
    'container.build_time' => 1516632675,
));
