<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW4O3aXF\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW4O3aXF/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerW4O3aXF.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerW4O3aXF\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerW4O3aXF\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'W4O3aXF',
    'container.build_id' => '4915b015',
    'container.build_time' => 1516634608,
));
